export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGIN_SUCCESS="LOGIN_SUCESS";
export const LOGIN_ERROR="LOGIN_ERROR";


//blogs

export const GET_BLOGS_REQUEST="GET_BLOGS_REQUEST";
export const GET_BLOGS_SUCCESS="GET_BLOGS_SUCCESS";
export const GET_BLOGS_ERROR="GET_BLOGS_ERROR";

export const ADD_BLOG_REQUEST="ADD_BLOG_REQUEST";

export const ADD_BLOG_SUCCESS="ADD_BLOG_SUCCESS";

export const ADD_BLOG_ERROR="ADD_BLOG_ERROR";

export const UPDATE_BLOG_REQUEST="UPDATE_BLOG_REQUEST";

export const UPDATE_BLOG_SUCCESS="UPDATE_BLOG_SUCCESS";

export const UPDATE_BLOG_ERROR="UPDATE_BLOG_ERROR";

export const DELETE_BLOG_REQUEST="DELETE_BLOG_REQUEST";

export const DELETE_BLOG_SUCCESS="DELETE_BLOG_SUCCESS";

export const DELETE_BLOG_ERROR="DELETE_BLOG_ERROR";
